title: Beta Wiki
tagline: "Technical Beta 1.7.3 Wiki"
description: A wiki documenting Minecraft Beta 1.7.3's technical specification and network protocol.
theme: just-the-docs
baseurl: ""
logo: "/assets/images/logo.png"

url: https://OfficialPixelBrush.github.io/beta-wiki
# favicon_ico: "/assets/images/favicon.ico"

color_scheme: custom
color_scheme_toggle: true
sass:
  style: compressed

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true
gh_edit_link_text: "✏️ Edit this page on GitHub."
gh_edit_branch: "main"
gh_edit_repository: "https://github.com/OfficialPixelBrush/beta-wiki"
gh_edit_view_mode: "edit"

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  # Use for warnings or erroneous info
  warning:
    title: Warning
    color: red
  # Use for notes or notices
  note:
    title: Note
    color: yellow
  # Use for missing info
  missing:
    title: Missing
    color: blue
  # Use for newly uncovered info
  new:
    title: New
    color: green
  # Use for unconfirmed info
  theory:
    title: Theory
    color: purple