export type AtlasKind = "blocks" | "items";

export type AtlasEntry = {
  atlas: AtlasKind;
  index: number;
};

/** Minecraft iconIndex: column + row * 16 on a 16×16 atlas. */
export const ATLAS_TILES = 16;

export const ATLAS_FILES: Record<AtlasKind, string> = {
  blocks: "/textures/terrain.png",
  items: "/textures/items.png",
};

/**
 * First atlas slot for each named 16×16 texture used by TextureSwatch.
 * Names match existing `texture_name` values (`blocks/stone`, `items/diamond_sword`).
 */
const BLOCK_INDEX: Record<string, number> = {
  grass_top: 0,
  stone: 1,
  dirt: 2,
  grass_side: 3,
  planks: 4,
  stone_slab_side: 5,
  stone_slab_top: 6,
  bricks: 7,
  tnt_side: 8,
  tnt_top: 9,
  tnt_bottom: 10,
  cobweb: 11,
  rose: 12,
  dandelion: 13,
  portal_placeholder: 14,
  oak_sapling: 15,
  cobblestone: 16,
  bedrock: 17,
  sand: 18,
  gravel: 19,
  oak_log_side: 20,
  log_top: 21,
  iron_block: 22,
  gold_block: 23,
  diamond_block: 24,
  chest_top: 25,
  chest_side: 26,
  chest_front: 27,
  red_mushroom: 28,
  brown_mushroom: 29,
  missing: 30,
  fire_placeholder: 31,
  gold_ore: 32,
  iron_ore: 33,
  coal_ore: 34,
  bookshelf: 35,
  mossy_cobblestone: 36,
  obsidian: 37,
  grass_side_overlay: 38,
  tallgrass: 39,
  double_chest_front_left: 41,
  double_chest_front_right: 42,
  crafting_table_top: 43,
  furnace_front: 44,
  furnace_dispenser_side: 45,
  dispenser_front: 46,
  sponge: 48,
  glass: 49,
  diamond_ore: 50,
  redstone_ore: 51,
  oak_leaves_transparent: 52,
  oak_leaves_opaque: 53,
  deadbush_shrub: 55,
  fern: 56,
  double_chest_back_left: 57,
  double_chest_back_right: 58,
  crafting_table_side_1: 59,
  crafting_table_side_2: 60,
  lit_furnace_front: 61,
  furnace_dispenser_top: 62,
  spruce_sapling: 63,
  white_wool: 64,
  mob_spawner: 65,
  snow: 66,
  ice: 67,
  grass_side_snow: 68,
  cactus_top: 69,
  cactus_side: 70,
  cactus_bottom: 71,
  clay: 72,
  sugarcane: 73,
  noteblock_jukebox: 74,
  jukebox_top: 75,
  birch_sapling: 79,
  torch: 80,
  wooden_door_top: 81,
  iron_door_top: 82,
  ladder: 83,
  trapdoor: 84,
  farmland_wet: 86,
  farmland_dry: 87,
  wheat_level_0: 88,
  wheat_level_1: 89,
  wheat_level_2: 90,
  wheat_level_3: 91,
  wheat_level_4: 92,
  wheat_level_5: 93,
  wheat_level_6: 94,
  wheat_level_7: 95,
  lever: 96,
  wooden_door_bottom: 97,
  iron_door_bottom: 98,
  redstone_torch_active: 99,
  pumpkin_top: 102,
  netherrack: 103,
  soul_sand: 104,
  glowstone: 105,
  sticky_piston_front: 106,
  piston_front: 107,
  piston_side: 108,
  piston_bottom: 109,
  piston_inside_front: 110,
  rail_turn: 112,
  black_wool: 113,
  dark_grey_wool: 114,
  redstone_torch_inactive: 115,
  spruce_log_side: 116,
  birch_log_side: 117,
  pumpkin_side: 118,
  pumpkin_front: 119,
  jack_o_lantern_front: 120,
  cake_top: 121,
  cake_outside: 122,
  cake_inside: 123,
  cake_bottom: 124,
  rail_straight: 128,
  red_wool: 129,
  pink_wool: 130,
  repeater_inactive: 131,
  spruce_leaves_transparent: 132,
  spruce_leaves_opaque: 133,
  bed_top_end: 134,
  bed_top_head: 135,
  cake_item: 140,
  lapis_lazuli_block: 144,
  dark_green_wool: 145,
  lime_wool: 146,
  repeater_active: 147,
  bed_front_end: 149,
  bed_side_end: 150,
  bed_side_head: 151,
  bed_front_head: 152,
  lapis_lazuli_ore: 160,
  brown_wool: 161,
  yellow_wool: 162,
  powered_rails_inactive: 163,
  redstone_cross: 164,
  redstone_line: 165,
  sandstone_top: 176,
  dark_blue_wool: 177,
  light_blue_wool: 178,
  powered_rails_active: 179,
  sandstone_side: 192,
  purple_wool: 193,
  magenta_wool: 194,
  activator_rail: 195,
  water_placeholder: 205,
  sandstone_bottom: 208,
  cyan_wool: 209,
  orange_wool: 210,
  grey_wool: 225,
  lava_placeholder: 237,
  block_breaking_level_0: 240,
  block_breaking_level_1: 241,
  block_breaking_level_2: 242,
  block_breaking_level_3: 243,
  block_breaking_level_4: 244,
  block_breaking_level_5: 245,
  block_breaking_level_6: 246,
  block_breaking_level_7: 247,
  block_breaking_level_8: 248,
  block_breaking_level_9: 249,
};

const ITEM_INDEX: Record<string, number> = {
  leather_helmet: 0,
  chainmail_helmet: 1,
  iron_helmet: 2,
  diamond_helmet: 3,
  gold_helmet: 4,
  flint_n_steel: 5,
  flint_and_steel: 5,
  flint: 6,
  coal: 7,
  string: 8,
  seeds: 9,
  apple: 10,
  golden_apple: 11,
  egg: 12,
  sugar: 13,
  snowball: 14,
  placeholder: 15,
  leather_chestplate: 16,
  chainmail_chestplate: 17,
  iron_chestplate: 18,
  diamond_chestplate: 19,
  gold_chestplate: 20,
  bow: 21,
  brick: 22,
  iron_ingot: 23,
  feather: 24,
  wheat: 25,
  painting: 26,
  sugarcane: 27,
  bone: 28,
  cake: 29,
  slimeball: 30,
  leather_leggings: 32,
  chainmail_leggings: 33,
  iron_leggings: 34,
  diamond_leggings: 35,
  gold_leggings: 36,
  arrow: 37,
  quiver: 38,
  gold_ingot: 39,
  gunpowder: 40,
  bread: 41,
  sign: 42,
  wooden_door: 43,
  iron_door: 44,
  bed: 45,
  leather_boots: 48,
  chainmail_boots: 49,
  iron_boots: 50,
  diamond_boots: 51,
  gold_boots: 52,
  stick: 53,
  compass: 54,
  diamond: 55,
  redstone_dust: 56,
  clay: 57,
  paper: 58,
  book: 59,
  map: 60,
  wooden_sword: 64,
  stone_sword: 65,
  iron_sword: 66,
  diamond_sword: 67,
  gold_sword: 68,
  fishing_rod: 69,
  clock: 70,
  bowl: 71,
  mushroom_stew: 72,
  glowstone_dust: 73,
  bucket: 74,
  water_bucket: 75,
  lava_bucket: 76,
  milk_bucket: 77,
  black_dye: 78,
  grey_dye: 79,
  wooden_shovel: 80,
  stone_shovel: 81,
  iron_shovel: 82,
  diamond_shovel: 83,
  gold_shovel: 84,
  repeater: 86,
  raw_porkchop: 87,
  cooked_porkchop: 88,
  raw_fish: 89,
  cooked_fish: 90,
  cookie: 92,
  shears: 93,
  red_dye: 94,
  pink_dye: 95,
  wooden_pickaxe: 96,
  stone_pickaxe: 97,
  iron_pickaxe: 98,
  diamond_pickaxe: 99,
  gold_pickaxe: 100,
  saddle: 104,
  leather: 103,
  green_dye: 110,
  lime_dye: 111,
  wooden_axe: 112,
  stone_axe: 113,
  iron_axe: 114,
  diamond_axe: 115,
  gold_axe: 116,
  brown_dye: 126,
  yellow_dye: 127,
  wooden_hoe: 128,
  stone_hoe: 129,
  iron_hoe: 130,
  diamond_hoe: 131,
  gold_hoe: 132,
  minecart: 135,
  boat: 136,
  blue_dye: 142,
  light_blue_dye: 143,
  chest_minecart: 151,
  purple_dye: 158,
  magenta_dye: 159,
  furnace_minecart: 167,
  cyan_dye: 174,
  orange_dye: 175,
  light_grey_dye: 190,
  bonemeal: 191,
  record_13: 240,
  record_cat: 241,
};

export function normalizeTextureName(name: string): string {
  return name.replace(/\.png$/i, "");
}

export function lookupTexture(name: string): AtlasEntry | undefined {
  const key = normalizeTextureName(name);
  const slash = key.indexOf("/");
  if (slash === -1) {
    return undefined;
  }

  const atlas = key.slice(0, slash);
  const id = key.slice(slash + 1);

  if (atlas === "blocks" && Object.prototype.hasOwnProperty.call(BLOCK_INDEX, id)) {
    return { atlas: "blocks", index: BLOCK_INDEX[id] };
  }

  if (atlas === "items" && Object.prototype.hasOwnProperty.call(ITEM_INDEX, id)) {
    return { atlas: "items", index: ITEM_INDEX[id] };
  }

  return undefined;
}

export function isAtlasKind(value: string): value is AtlasKind {
  return value === "blocks" || value === "items";
}
